pipeline {
    agent any

    stages {
        
        stage('Run Tests') {
            steps {
                sh './mvn clean install test -Dcucumber.options="--plugin json:target/cucumber-report.json"'
            }
        }
        
}
}